language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build


deploy:
  provider: s3
  access_key_id: AKIAIGD77HFYDYZN5BVQ
  endpoint: s3-website.eu-west-3.amazonaws.com
  region: eu-west-3
  secret_access_key:
    secure: tEmLRmcCfULYVaN2sDDNLGVGKMi0+8Mgc7xUePDmDGU1OSwhPToDEQtVoBiRn+gn++CpYClpQwY8xWeFjZ/bhoTAtjkQpswSBV1TIHRb7KkgEMImEloIysLiVbkRNztzhGFmDklw5EhG3Z8Xn9h8ZG2mx7DrtJQoKRDnZzsvOEGQURgC9JieBX4F+ezn6a8bbPomW46FGjjLaTLXhOw9NMrD6HbjENrfPD/613JixVKkNUZtzjtT9jz7+sr1yu8x0741cucyWnhZNkHyKpuKBrah1LNhSk1dVIW1Of0mmqZfzk3P5mCv+UCaK0wfIY5WkvwlofKMcnNN6OQrMocFfHf80CGMAthD13dz6b6HwCCDMzAtPQfTpLoyd8R06KCDl/oB9I3p7ZBtboH0iCrIQPvSnYkxUEZGUgkqS3LetSUMxSipp3I1k5dneFKlrGYn+SDZhRgD4i/wLd7mNrpl8ajDs2DV2GxDXm35mYuLvjp3PysF0bOXI28xhyjYwy5A4a4r6IwvD/CfGzFke2TKDTQ0WqVf4o/8vD8MLh6sXilzy170WxXEVAfIjpOzQOAa4jJt1T3iz1l6JirSbd9BoMWXmAwjOh2ASD7UNSk6nG4nZyZomYNfF/dpbijCdz3N0UXgy/owuoQJeXqIu4NgZvMHkwC9rwqNFqPeixCNB7A=
  bucket: github-requester
  local-dir: build
  skip_cleanup: true
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/github-requester
