language: node_js
node_js:
  - node

install:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAI6IKW3HG5C6XRL4A
  endpoint: s3-website.eu-west-3.amazonaws.com
  region: eu-west-3
  secret_access_key:
    secure: K+vYr/ur/zy1UwRYZJWsMo+og2Kc/LECELVx+6XwIHx7oTvyASUNex1EnRQvuALmdZvsigywntIV3rwujjaDm9IHs8JzJMHC5dtYZ1kBhzpWDF0G1dJIfg17U2lsxJWFdjEWDzjYtKsZ00u0YP1AhSHdMXY7IeYGAGFzIyy3agHIiomNTAS4CbCzZ0mLvZA+ivyJTBpSWAmMBFC6z+Vzo4IXRpQ9ZE0egZwzw/KLLAc8uqsTi+fu25lSB9DzYbTs9arh5bZIcgEt7NdIhz85hyhhmkxThHfCX/w9zoyJG2bnn7rbBsPrxbEefwcrKp1eq/dp1tdbKcJy6Ov8vmxm4LA5x99eQG9IesjQC/xTXu2B2AhwER66AY+AVqzZGSZnm2myet6kAU7CLdqU0x0rZLcCX4J03rqrsart+kMlfUavLSvC2NQLmpeJNlfr+2yCFnT48k4h9jWkew/wK1u4d0hO1z5zvoXExDkoxCCQbhTgXUPVvrXc87E4UwJXPf+GhIw0T9PVczyjdytwztUvxkiumxad35cKXbbU4NatTCyq8aETf2eCEk/nldu0n7hzm6fFwX3rORJcRo+NZ8kdsjl9lm+UlNqDVbyc2xEpDbG8MnErpvwOXeDrut6AbJVMMVGHohMcSfoU7CBjAtbXt/tyQOCXKG4R/K9g2aaDYhY=
  bucket: github-requester
  local-dir: build
  skip_cleanup: true
  acl: bucket_owner_full_control
  on:
    repo: GaelWM/github-requester
